In [1]:
from skimage import feature
from matplotlib import pyplot as plt

import numpy as np
from sklearn.svm import LinearSVC
from imutils import paths
import argparse
import cv2
from keras.datasets import cifar10


Using TensorFlow backend.


In [2]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

In [3]:
numPoints = 24
radius = 8
def describe(image, eps=1e-7):
# compute the Local Binary Pattern representation
# of the image, and then use the LBP representation
# to build the histogram of patterns
    lbp = feature.local_binary_pattern(image,numPoints,radius, method="uniform")
    (hist, _) = np.histogram(lbp.ravel(),bins=np.arange(0, numPoints + 3), range=(0, numPoints + 2)) 
# normalize the histogram
    hist = hist.astype("float")
    hist /= (hist.sum() + eps)
 
    # return the histogram of Local Binary Patterns
    return hist

In [4]:
data = []
labels = []
for i in range(0,x_train.shape[0]):
    img = x_train[i]
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    hist = describe(gray)
    labels.append(y_train[i])
    data.append(hist)
#     print(hist.shape)
#     break
    
    

In [5]:
# train a Linear SVM on the data
model = LinearSVC(C=100.0, random_state=42,verbose= True)
model.fit(data, labels)

/home/anirudh/detect/lib/python3.5/site-packages/sklearn/utils/validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibLinear]

/home/anirudh/detect/lib/python3.5/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=100.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=42, tol=0.0001,
     verbose=True)

In [6]:
acc = [] 
# loop over the testing images
for i in range(0,x_test.shape[0]):
    img = x_test[i]
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    hist = describe(gray)
    prediction = model.predict(hist.reshape(1, -1))
    acc.append(prediction == y_test[i])

In [7]:
np.mean(acc)


0.2324

In [8]:
acc

[array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([ True]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([ True]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([False]